apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: yohpal-live-secret-store
  namespace: yohpal-live
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa