apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yohpal-live-external-secrets
  namespace: yohpal-live
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: yohpal-live-secret-store
    kind: SecretStore
  target:
    name: yohpal-live-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: yohpal-live/production
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: yohpal-live/production
        property: REDIS_URL
    - secretKey: ADMIN_JWT_SECRET
      remoteRef:
        key: yohpal-live/production
        property: ADMIN_JWT_SECRET
    - secretKey: API_GATEWAY_KEY
      remoteRef:
        key: yohpal-live/production
        property: API_GATEWAY_KEY
    - secretKey: SERVICE_AUTH_KEY
      remoteRef:
        key: yohpal-live/production
        property: SERVICE_AUTH_KEY
    - secretKey: AI_GATEWAY_URL
      remoteRef:
        key: yohpal-live/production
        property: AI_GATEWAY_URL