export type ScriptPromptInput = {
  topic: string;
  category: string;
  region?: string | null;
  country?: string | null;
  audience?: string;
  language?: string;
  durationSeconds?: number;
};
export function buildSeedVideoScriptPrompt(input: ScriptPromptInput): string {
  return `
You are YohPal Live AI Content Factory.
Create a safe, engaging short-video script for YohPal Live.
Topic: ${input.topic}
Category: ${input.category}
Region: ${input.region || "General"}
Country: ${input.country || "General"}
Audience: ${input.audience || "African youth, students, creators, job seekers, and small business owners"}
Language: ${input.language || "en"}
Target Duration: ${input.durationSeconds || 45} seconds
Rules:
1. Start with a strong hook.
2. Use simple, friendly, energetic language.
3. Avoid hate, insults, explicit content, political manipulation, medical claims, legal claims, or financial
promises.
4. Keep it suitable for early YohPal Live users.
5. Add a soft call-to-action at the end.
6. Do not mention that this content was generated by AI.
`;
}
export function buildFactCheckPrompt(script: string): string {
  return `
Review the following YohPal Live seed video script for factual safety.
Script:
${script}
Return:
1. factScore from 0 to 1
2. unsafeClaims list
3. correctionNotes
4. requiresHumanReview true/false
`;
}
export function buildViralPredictionPrompt(script: string): string {
  return `
Score this YohPal Live short-video script for potential performance.
Script:
${script}
Return scores from 0 to 1 for:
1. viralProbability
2. engagementScore
3. watchTimeScore
4. shareScore
5. commentScore
6. qualityScore
`;
}
